### ISSUE TITLE
clio pushw -e Enviroment

### ISSUE THREAD

**Issue by unusen** [Advance-Technologies-Foundation/clio#308]
Hello Clio team! How are you? We are working collaboratively and we are encountering some problems where taking changes from a repo or even making changes locally to the files and bringing them to the local environment with the clio pushw command. These changes are not reflected in Creatio.
Below an example:

1. We did a simple change on Accounts_FormPage.js to test addind a comment in Creatio:
define("Accounts_FormPage", /**SCHEMA_DEPS*/["@creatio-devkit/common"]/**SCHEMA_DEPS*/, function/**SCHEMA_ARGS*/(sdk)/**SCHEMA_ARGS*/ {
	return {**//aaaa**

2. We use Clio Restorew -e enviroment to get this change locally and everything works as expected
3. We add to this comment another text for example "aaaabbbb"
4. We executed  Clio pushw -e Enviroment (see the logs) and nothing change on Creatio side

This is a simple test trying to simulate that the change comes from another developer. This was working a few weeks ago when we started working with this approach, but now we noticed that some changes from our developers were not reflected in the different environments.
[Log.txt](https://github.com/user-attachments/files/16728937/Log.txt)
![vscode](https://github.com/user-attachments/assets/b5c8a332-000f-454e-af55-14bff1ba517a)
![Creatio](https://github.com/user-attachments/assets/9b55daa5-32ab-450d-a05c-ea12ec708b86)

I appreciate your help and continued improvements to clio.

**Comment by vladimir-nikonov** [comment]
Hello, can you provide details about the environment you are using? We are interested in what mode (FileDesign or not) works in the target environment because there can be situations when the target environment is in FileDesignMode. In these cases. We recommended for system with active fileDesignMode  use functionality to link Workspace to your Pkg folder via the command 
`clio link-from-repository -e "{LOCAL_CREATIO_PATH}Terrasoft.WebApp\Terrasoft.Configuration\Pkg" -r "C:\Workspaces\MyWorkspace\packages"`

**Comment by unusen** [comment]
@vladimir-nikonov  thank you! It seems that the problem occurs when FileDesignMode is active.
I will continue testing to understand if deactivating it really solves it.
Appreciate it
Regards.
